version: '3'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: new_user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - test_network
      
  theatre-service:
    image: aditikatiyar/theatreapp:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://new_user:password@mongo:27017/theatre?authSource=admin"    
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - test_network
      
networks:
    test_network:
      driver: bridge
      
volumes:
    mongo-data: