version: '3'

services:
   booking-service:
    image: aditikatiyar/bookingapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: "172.24.0.4:9092"
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_CONSUMER_GROUP_ID: my-consumer-group
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC: movie-topic
    ports:
      - "8082:8082"
    networks:
      - test_network
      
networks:
    test_network:
      driver: bridge