version: '3'

services:
   booking-service:
    image: aditikatiyar/bookingapp:v3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      SPRING_KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      SPRING_KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka:9092"
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
    ports:
      - "8089:8089"
    networks:
      - test_network
      
networks:
    test_network:
      driver: bridge